### ISSUE TITLE
Explore generative AI tools for graphics

### ISSUE THREAD

**Issue by umut-sahin** [umut-sahin/mythmallow#69]
## Goal
To utilize AI to generate graphics for fast prototyping. It needs to be able to create smooth animations of multiple players/enemies/items/more in a consistent style.

## Resources
- https://openai.com/index/dall-e-3/
- https://www.rosebud.ai/blog/ai-game-assets-generator-pixelvibe
- https://github.com/mxgmn/WaveFunctionCollapse
- https://www.pixellab.ai/
- https://astropulse.gumroad.com/l/RetroDiffusion
- more?

**Comment by ElessaR-x** [comment]
### Summary

- Dall-E's current capabilities are not yet suitable for our requirements.
- Pixel Art is not preferred for this project.
- Other AI tools have been found to be inadequate for our needs.

### Examples

![Hades_Mythmallow_Character](https://github.com/umut-sahin/mythmallow/assets/67552866/7a9d8055-e430-444b-bc1e-4f43f5af2bfa)
![Hades_Mythmallow_Cleaned](https://github.com/umut-sahin/mythmallow/assets/67552866/835ff4e0-1c26-4286-82f3-c6aa61da15ac)
